# Generated by Django 6.0.2 on 2026-02-27 15:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique_for_date='created_at', verbose_name='Название задачи')),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(500)], verbose_name='Описание задачи')),
                ('status', models.CharField(choices=[('New', 'NEW STATUS'), ('In progress', 'IN PROGRESS STATUS'), ('Pending', 'PENDING STATUS'), ('Blocked', 'BLOCKED STATUS'), ('Done', 'DONE STATUS')], max_length=20, verbose_name='Статус задачи')),
                ('deadline', models.DateTimeField(verbose_name='Дата и время дедлайн')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('categories', models.ManyToManyField(related_name='tasks', to='my_app.category', verbose_name='Категории задачи')),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название подзадачи')),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(500)], verbose_name='Описание подзадачи')),
                ('status', models.CharField(choices=[('New', 'NEW STATUS'), ('In progress', 'IN PROGRESS STATUS'), ('Pending', 'PENDING STATUS'), ('Blocked', 'BLOCKED STATUS'), ('Done', 'DONE STATUS')], max_length=20, verbose_name='Статус задачи')),
                ('deadline', models.DateTimeField(verbose_name='Дата и время дедлайн')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subtasks', to='my_app.task')),
            ],
        ),
    ]
