# Generated by Django 6.0.2 on 2026-04-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_category_options_alter_subtask_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('New', 'NEW STATUS'), ('In progress', 'IN PROGRESS STATUS'), ('Pending', 'PENDING STATUS'), ('Blocked', 'BLOCKED STATUS'), ('Done', 'DONE STATUS')], default='New', max_length=20, verbose_name='Статус задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('New', 'NEW STATUS'), ('In progress', 'IN PROGRESS STATUS'), ('Pending', 'PENDING STATUS'), ('Blocked', 'BLOCKED STATUS'), ('Done', 'DONE STATUS')], default='New', max_length=20, verbose_name='Статус задачи'),
        ),
    ]
